      - name: Overwrite package.json build config (put full python under resources)
        shell: pwsh
        working-directory: ${{ env.APP_DIR }}
        run: |
          $pkg = Get-Content package.json -Raw | ConvertFrom-Json
          $pkg.build = @{
            appId           = "com.evi.brush.desktop";
            productName     = "EVI Brush Desktop";
            directories     = @{ output = "dist" };

            # ✅ app.asar 內只放前端/JS，不放 python
            files           = @(
              "**/*",
              "!python/**",     # ← 把整個 python 從 app 區域排除
              "!logs/**","!.github/**","!**/*.log","!**/*.md"
            );

            # ✅ 把 repo 的 python 整包（含 venv、server.py、models）放到 resources\python\
            extraResources  = @(
              @{ from = "python"; to = "python"; filter = @("**/*") }
            );

            # 現在先用 asar:false 好檢查；穩定後可改回 true
            asar            = $false;

            win  = @{ icon="build/icon.ico"; target=@("nsis") };
            nsis = @{
              oneClick = $true; perMachine = $false;
              allowToChangeInstallationDirectory = $false;
              createDesktopShortcut = $true; createStartMenuShortcut = $true;
              shortcutName = "EVI Brush Desktop"; runAfterFinish = $true;
              uninstallDisplayName = "EVI Brush Desktop"
            };
            publish = @(@{ provider = "github" })
          }
          ($pkg | ConvertTo-Json -Depth 100) | Set-Content package.json -Encoding UTF8
