name: Build Desktop App (Win, no publish)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node deps
        shell: pwsh
        run: |
          npm i

      - name: Ensure pbs marker & folders (optional)
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path "logs" | Out-Null
          New-Item -ItemType Directory -Force -Path "python\models\sd-turbo" | Out-Null
          New-Item -ItemType File -Force -Path "python\pbs" | Out-Null

      - name: Build (no publish)
        shell: pwsh
        env:
          DEBUG: "electron-builder"
        run: |
          npx electron-builder --win --x64 --publish never 2>&1 | Tee-Object -FilePath "$env:GITHUB_WORKSPACE\logs\eb.log"

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: logs/*.log

      - name: Upload installers
        uses: actions/upload-artifact@v4
        with:
          name: installer-windows
          path: |
            dist/*.exe
            dist/*.msi
            dist/*.zip
            dist/*.7z
