name: Build Desktop App (Win, no publish)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      APP_DIR: ${{ github.workspace }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # 不要設定 cache，否則沒有 lockfile 會報錯

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Ensure python/pbs folder (safe)
        shell: pwsh
        working-directory: ${{ env.APP_DIR }}
        run: |
          $py  = Join-Path $pwd 'python'
          $pbs = Join-Path $py  'pbs'
          if (-not (Test-Path $pbs)) { New-Item -Path $pbs -ItemType Directory -Force | Out-Null }
          Set-Content -LiteralPath (Join-Path $pbs 'ok') -Value 'ok' -Encoding Ascii

      - name: Download SDXL-Turbo model
        shell: pwsh
        working-directory: ${{ env.APP_DIR }}
        env:
          HF_HUB_ENABLE_HF_TRANSFER: '1'
        run: |
          python -m pip install --upgrade pip
          pip install "huggingface_hub[hf_transfer]"
          python - <<'PY'
          from huggingface_hub import snapshot_download
          from pathlib import Path
          p = Path("python/models/sd-turbo")
          p.mkdir(parents=True, exist_ok=True)
          snapshot_download(repo_id="stabilityai/sdxl-turbo",
                            local_dir=str(p), local_dir_use_symlinks=False)
          print("model ok")
          PY

      - name: Build (no publish)
        shell: pwsh
        working-directory: ${{ env.APP_DIR }}
        run: |
          New-Item -ItemType Directory -Force -Path logs | Out-Null
          $ErrorActionPreference = 'Stop'
          npx --yes electron-builder@24.13.3 --win --x64 --publish never *>&1 `
            | Tee-Object -LiteralPath "$env:GITHUB_WORKSPACE\logs\eb.log"

      - name: Upload installers
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: installer-windows
          path: |
            dist\*.exe
            dist\*.msi
            dist\*.zip
          if-no-files-found: warn

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: logs\**\*.log
          if-no-files-found: warn
