name: Build Desktop App (Win, no publish)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 只安裝 Node，不做 cache（避免沒有 lock 檔時出錯）
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node deps
        run: |
          if (Test-Path 'package.json') {
            if (Test-Path 'package-lock.json') { npm ci } else { npm i }
          } else {
            Write-Host "No package.json — skip npm install"
          }

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 一定會先建立 python/pbs 目錄，再寫入 ok 檔
      - name: Ensure python/pbs folder (safe)
        run: |
          $pbs = Join-Path $env:GITHUB_WORKSPACE 'python\pbs'
          New-Item -ItemType Directory -Force -Path $pbs | Out-Null
          Set-Content -Path (Join-Path $pbs 'ok') -Value 'ok' -Encoding ascii

      - name: Build (no publish)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx --yes electron-builder --win --x64 --publish never

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: eb.log
          path: |
            dist\*.exe
            dist\*.msi
            logs\**\*.log
          if-no-files-found: warn
