name: Build Desktop App (Win, no publish)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'   # 不設定 cache，就不會要求 lock 檔

      - name: Install Node deps (skip if no package.json)
        run: |
          if (Test-Path 'package.json') {
            if (Test-Path 'package-lock.json') { npm ci } else { npm i }
          } else {
            Write-Host 'No package.json; skip npm install.'
          }

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Ensure python/pbs & model folders (safe)
        run: |
          $ErrorActionPreference = 'Stop'
          $root   = $pwd
          $py     = Join-Path $root 'python'
          $pbs    = Join-Path $py 'pbs'
          $models = Join-Path $py 'models'
          $sd     = Join-Path $models 'sd-turbo'

          New-Item -ItemType Directory -Force -Path $py     | Out-Null
          New-Item -ItemType Directory -Force -Path $pbs    | Out-Null
          New-Item -ItemType Directory -Force -Path $models | Out-Null
          New-Item -ItemType Directory -Force -Path $sd     | Out-Null

          Set-Content -Path (Join-Path $pbs 'ok') -Value 'ok' -Encoding ascii
          Write-Host "Prepared python/pbs and models folders."

      - name: Build (no publish)
        env:
          DEBUG: electron-builder
        run: |
          npx electron-builder --win --x64 --publish never

      - name: Upload installers
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: installers
          path: |
            dist\*.exe
            dist\*.msi
            dist\*.zip
          if-no-files-found: ignore

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: logs\**\*.log
          if-no-files-found: ignore
