name: Build Desktop App (Win, no publish)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 180

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 不使用 cache，避免要求有 lockfile（package-lock / yarn.lock）
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node dependencies
        shell: pwsh
        run: |
          if (Test-Path package-lock.json) { npm ci } else { npm i }

      # 可選：確保 icon 存在（若你已把 build/icon.ico commit 進 repo，可保留或刪除此步）
      - name: Ensure icon exists (optional)
        shell: pwsh
        run: |
          if (-not (Test-Path build\icon.ico)) {
            New-Item -ItemType Directory -Path build -Force | Out-Null
            (New-Object Net.WebClient).DownloadFile(
              'https://raw.githubusercontent.com/electron/electron/main/docs/images/icons/win/icon.ico',
              'build\icon.ico'
            )
          }

      - name: Build (no publish)
        shell: pwsh
        env:
          DEBUG: "electron-builder"
        run: |
          npx electron-builder --win --x64 --publish never *> $env:GITHUB_WORKSPACE/eb.log
          if (-not (Test-Path dist)) { throw "No installers produced." }
          Get-ChildItem dist -Recurse | % { Write-Host "artifact $($_.FullName)" }

      - name: Upload installers
        uses: actions/upload-artifact@v4
        with:
          name: installer-windows
          path: dist/**

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            eb.log
            **\*.log
