name: Build Desktop App (Win, no publish)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 只有有 package.json 才裝依賴
      - name: Install Node deps (skip if no package.json)
        if: ${{ hashFiles('package.json') != '' }}
        shell: pwsh
        run: |
          if (Test-Path package-lock.json) { npm ci } else { npm i }

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # ✅ 以 .NET 方式遞迴建立 python\pbs，再寫入 ok 標記
      - name: Ensure python/pbs folder (safe)
        shell: pwsh
        run: |
          $root   = (Get-Location).Path
          $pbsDir = Join-Path $root 'python\pbs'
          [System.IO.Directory]::CreateDirectory($pbsDir) | Out-Null
          $ok = Join-Path $pbsDir 'ok'
          Set-Content -LiteralPath $ok -Value 'ok' -Encoding ascii -Force
          Write-Host "Created $ok"

      - name: Build (no publish)
        if: ${{ hashFiles('package.json') != '' }}
        shell: pwsh
        run: npx electron-builder --win --x64 --publish never

      # 收集 npm 日誌到工作區再上傳（避免 rootDirectory 問題）
      - name: Collect npm logs (best-effort)
        shell: pwsh
        run: |
          $dst = Join-Path (Get-Location).Path 'logs\npm'
          [System.IO.Directory]::CreateDirectory($dst) | Out-Null
          $cands = @('C:\npm\_logs', "$env:USERPROFILE\AppData\Local\npm-cache\_logs")
          foreach ($p in $cands) {
            if (Test-Path $p) {
              Get-ChildItem -Path $p -Recurse -File -ErrorAction SilentlyContinue |
                Copy-Item -Destination $dst -Force -ErrorAction SilentlyContinue
            }
          }
          Write-Host "Logs copied to $dst"

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/**/*
          if-no-files-found: ignore
