name: Build Desktop App (Win, no publish)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      APP_DIR: ${{ github.workspace }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node deps (skip if no package.json)
        shell: pwsh
        run: |
          if (Test-Path 'package.json') {
            if (Test-Path 'package-lock.json') { npm ci } else { npm i }
          } else {
            Write-Host 'No package.json; skip npm install.'
          }

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Ensure python/pbs folder (safe)
        shell: pwsh
        run: |
          $root = "${{ env.APP_DIR }}"
          $py   = Join-Path $root 'python'
          $pbs  = Join-Path $py   'pbs'
          New-Item -ItemType Directory -Force -Path $py,$pbs | Out-Null
          # 放一個 marker，避免後續步驟誤判資料夾不存在
          Set-Content -LiteralPath (Join-Path $pbs 'ok') -Value 'ok' -Encoding ascii

      # 如果要試 build（專案有 package.json 才會做）
      - name: Build (no publish)
        if: ${{ hashFiles('package.json') != '' }}
        shell: pwsh
        run: |
          npx electron-builder --win --x64 --publish never

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: |
            logs\**\*.log
          if-no-files-found: ignore
