name: Build Desktop App (Win, no publish)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 有 package.json 才安裝
      - name: Install Node deps (skip if no package.json)
        if: ${{ hashFiles('package.json') != '' }}
        shell: pwsh
        run: |
          if (Test-Path package-lock.json) { npm ci } else { npm i }

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # ✅ 穩健建立 python\pbs：若同名為檔案則移除後建資料夾
      - name: Ensure python/pbs folder (safe)
        shell: pwsh
        run: |
          $root   = (Get-Location).Path
          $pyDir  = Join-Path $root 'python'
          $pbsDir = Join-Path $pyDir  'pbs'

          # 確保 python 是資料夾
          if (Test-Path $pyDir) {
            $it = Get-Item $pyDir -ErrorAction SilentlyContinue
            if ($it -and -not $it.PSIsContainer) { Remove-Item $pyDir -Force }
          }
          New-Item -ItemType Directory -Path $pyDir -Force | Out-Null

          # 若 pbs 是檔案則移除
          if (Test-Path $pbsDir) {
            $it = Get-Item $pbsDir -ErrorAction SilentlyContinue
            if ($it -and -not $it.PSIsContainer) { Remove-Item $pbsDir -Force }
          }
          New-Item -ItemType Directory -Path $pbsDir -Force | Out-Null

          $ok = Join-Path $pbsDir 'ok'
          Set-Content -LiteralPath $ok -Value 'ok' -Encoding ascii -Force
          Write-Host "Prepared $pbsDir and wrote $ok"

      - name: Build (no publish)
        if: ${{ hashFiles('package.json') != '' }}
        shell: pwsh
        run: npx electron-builder --win --x64 --publish never

      # 收集 npm logs 到工作區
      - name: Collect npm logs (best-effort)
        shell: pwsh
        run: |
          $dst = Join-Path (Get-Location).Path 'logs\npm'
          New-Item -ItemType Directory -Path $dst -Force | Out-Null
          $cands = @('C:\npm\_logs', "$env:USERPROFILE\AppData\Local\npm-cache\_logs")
          foreach ($p in $cands) {
            if (Test-Path $p) {
              Get-ChildItem -Path $p -Recurse -File -ErrorAction SilentlyContinue |
                Copy-Item -Destination $dst -Force -ErrorAction SilentlyContinue
            }
          }

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/**/*
          if-no-files-found: ignore
