name: Build Desktop App (Win, no publish)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 90
    env:
      APP_DIR: ${{ github.workspace }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable npm cache if lockfile exists
        if: ${{ hashFiles('package-lock.json') != '' }}
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install Node deps
        shell: pwsh
        run: |
          if (Test-Path 'package-lock.json') { npm ci } else { npm i }

      - name: Ensure pbs marker exists
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path "python" | Out-Null
          Set-Content -Path "python/pbs" -Value "ok" -Encoding ascii

      - name: Build (no publish)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          npx electron-builder --win --x64 --publish=never *>&1 | Tee-Object -FilePath "$env:GITHUB_WORKSPACE\eb.log"

      - name: Upload installers
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: installer-windows
          path: dist/*

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            eb.log
            **\*.log
