name: Release (Win + model, SMOKE)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/release.yml  # 只要這檔有變更就會觸發一次

jobs:
  smoke:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Say hello
        shell: pwsh
        run: |
          Write-Host "Smoke workflow is visible & working."
