name: Release (Win + model, GitHub Releases)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Optional tag (e.g. v0.1.0). Leave empty to skip tagging.'
        required: false
        default: ''

jobs:
  release-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'   # 不設定 cache，避免 lock 檔錯誤

      - name: Install Node deps (skip if no package.json)
        run: |
          if (Test-Path 'package.json') {
            if (Test-Path 'package-lock.json') { npm ci } else { npm i }
          } else {
            Write-Host 'No package.json; skip npm install.'
          }

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Ensure pbs & model folders (safe)
        run: |
          $ErrorActionPreference = 'Stop'
          $root   = $pwd
          $py     = Join-Path $root 'python'
          $pbs    = Join-Path $py 'pbs'
          $models = Join-Path $py 'models'
          $sd     = Join-Path $models 'sd-turbo'

          New-Item -ItemType Directory -Force -Path $py     | Out-Null
          New-Item -ItemType Directory -Force -Path $pbs    | Out-Null
          New-Item -ItemType Directory -Force -Path $models | Out-Null
          New-Item -ItemType Directory -Force -Path $sd     | Out-Null

          Set-Content -Path (Join-Path $pbs 'ok') -Value 'ok' -Encoding ascii

      - name: Download SDXL-Turbo model -> python/models/sd-turbo
        run: |
          $ErrorActionPreference = 'Stop'
          python -m pip install --upgrade pip
          python -m pip install "huggingface_hub>=0.23" hf_transfer

          $sd = Join-Path (Join-Path $pwd 'python\models') 'sd-turbo'
          New-Item -ItemType Directory -Force -Path $sd | Out-Null

          $code = @"
from huggingface_hub import snapshot_download
import os
target = r"$sd"
os.makedirs(target, exist_ok=True)
snapshot_download(
    repo_id="stabilityai/sdxl-turbo",
    local_dir=target,
    local_dir_use_symlinks=False
)
print("Model saved to:", target)
"@

          $tmp = Join-Path $env:RUNNER_TEMP 'download_model.py'
          Set-Content -Path $tmp -Value $code -Encoding UTF8
          python $tmp

      - name: Create tag (optional)
        if: ${{ github.event.inputs.tag != '' }}
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"
          git tag $env:TAG
          git push origin $env:TAG
        env:
          TAG: ${{ github.event.inputs.tag }}

      - name: Build & publish (GitHub Releases)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: electron-builder
        run: |
          npx electron-builder --win --x64 --publish always

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: release-logs
          path: logs\**\*.log
          if-no-files-found: ignore
