name: Release (Win + model, GitHub Releases)

on:
  workflow_dispatch:

jobs:
  release-windows:
    runs-on: windows-latest
    env:
      APP_DIR: ${{ github.workspace }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node deps (skip if no package.json)
        if: ${{ hashFiles('**/package.json') != '' }}
        shell: pwsh
        run: |
          if (Test-Path package-lock.json) { npm ci } else { npm i }

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Ensure pbs & model folders (safe)
        shell: pwsh
        run: |
          $root   = "${{ github.workspace }}"
          $pyRoot = Join-Path $root 'python'
          $pbsDir = Join-Path $pyRoot 'pbs'
          $mdlDir = Join-Path $pyRoot 'models\sd-turbo'
          New-Item -ItemType Directory -Force -Path $pbsDir | Out-Null
          New-Item -ItemType Directory -Force -Path $mdlDir | Out-Null
          Set-Content -LiteralPath (Join-Path $pbsDir 'ok') -Value 'ok' -Encoding ascii

      - name: Download SDXL-Turbo model
        shell: pwsh
        run: |
          python -m pip install -U huggingface_hub hf_transfer
          python - <<'PY'
          from pathlib import Path
          from huggingface_hub import snapshot_download
          tgt = Path("python/models/sd-turbo")
          tgt.mkdir(parents=True, exist_ok=True)
          snapshot_download(repo_id="stabilityai/sdxl-turbo",
                            local_dir=str(tgt),
                            local_dir_use_symlinks=False)
          print("Model saved to:", tgt)
          PY

      - name: Build & publish (electron-builder)
        if: ${{ hashFiles('**/package.json') != '' }}
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $ErrorActionPreference = 'Stop'
          New-Item -ItemType Directory -Force -Path "logs" | Out-Null
          npx electron-builder --win --x64 *> "logs/eb.log"

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs\**\*.log

      - name: Create GitHub Release
        if: always()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          files: |
            dist\*.exe
            dist\*.msi
            dist\*.zip
