name: Release (App + Model, split)

on:
  workflow_dispatch:

jobs:
  release-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node deps (skip if no package.json)
        if: ${{ hashFiles('package.json') != '' }}
        shell: pwsh
        run: |
          if (Test-Path package-lock.json) { npm ci } else { npm i }

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 建立 python\pbs 與模型資料夾（穩健）
      - name: Ensure python/pbs & model folders (safe)
        shell: pwsh
        run: |
          $root   = (Get-Location).Path
          $pyDir  = Join-Path $root 'python'
          $pbsDir = Join-Path $pyDir  'pbs'
          $mdlDir = Join-Path $pyDir  'models\sd-turbo'
          foreach ($d in @($pyDir,$pbsDir,$mdlDir)) {
            if (Test-Path $d) {
              $it = Get-Item $d -ErrorAction SilentlyContinue
              if ($it -and -not $it.PSIsContainer) { Remove-Item $d -Force }
            }
            New-Item -ItemType Directory -Path $d -Force | Out-Null
          }
          Set-Content -LiteralPath (Join-Path $pbsDir 'ok') -Value 'ok' -Encoding ascii -Force

      # -------------------------
      # 先建 APP（NSIS + Portable）
      # -------------------------
      - name: Build App (nsis + portable)
        if: ${{ hashFiles('package.json') != '' }}
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx electron-builder --win --x64 --publish never

      - name: Compute tag
        id: tag
        shell: pwsh
        run: |
          $tag = "v$($Env:GITHUB_RUN_NUMBER)"
          echo "tag=$tag" >> $env:GITHUB_OUTPUT

      - name: Create/Update Release (App assets)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: ${{ steps.tag.outputs.tag }}
          draft: false
          prerelease: false
          files: |
            dist/*-x64-portable.exe
            dist/*Setup*.exe

      # -------------------------
      # 打包模型與分卷上傳
      # -------------------------
      - name: Install deps for model download
        shell: pwsh
        run: |
          python -m pip install -U pip
          python -m pip install "huggingface_hub>=0.22.0" hf_transfer

      - name: Download SDXL-Turbo model
        shell: pwsh
        env:
          HF_ENDPOINT: https://huggingface.co
        run: |
          $target = Join-Path (Get-Location).Path 'python\models\sd-turbo'
          $code = @'
          from huggingface_hub import snapshot_download
          import os
          tgt = os.environ["TARGET_DIR"]
          snapshot_download(
              repo_id="stabilityai/sdxl-turbo",
              local_dir=tgt,
              local_dir_use_symlinks=False
          )
          print("Model saved to:", tgt)
          '@
          Set-Content -Path download_model.py -Value $code -Encoding UTF8
          $env:TARGET_DIR = $target
          python download_model.py

      - name: Pack model into 7z (split 1900MB parts)
        shell: pwsh
        run: |
          $out = Join-Path (Get-Location).Path 'dist\model'
          New-Item -ItemType Directory -Path $out -Force | Out-Null
          $sevenZip = "C:\Program Files\7-Zip\7z.exe"
          & $sevenZip a -t7z -mx=3 -v1900m "$out\model-pack.7z" ".\python\models\sd-turbo\*" | Write-Host

      - name: Upload model pack parts to the same Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          files: dist/model/model-pack.7z.*

      #（可選）模型下載 log
      - name: Upload logs (best-effort)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: |
            C:\npm\_logs\**
            $HOME\AppData\Local\npm-cache\_logs\**
          if-no-files-found: ignore
