name: Release (App + Model, 900MB split)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (ex: v73). 留空則自動產生 v{run_number}'
        required: false
        default: ''
      prerelease:
        description: '是否當作 Pre-release'
        type: boolean
        required: false
        default: false

jobs:
  release-windows:
    runs-on: windows-latest

    env:
      NODE_OPTIONS: --max_old_space_size=4096
      HF_ENDPOINT: https://huggingface.co

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node deps (skip if no package.json)
        if: ${{ hashFiles('package.json') != '' }}
        shell: pwsh
        run: |
          if (Test-Path package-lock.json) { npm ci } else { npm i }

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Ensure pbs & model folders (safe)
        shell: pwsh
        run: |
          $root   = (Get-Location).Path
          $pyDir  = Join-Path $root 'python'
          $pbsDir = Join-Path $pyDir  'pbs'
          $mdlDir = Join-Path $pyDir  'models\sd-turbo'
          foreach ($d in @($pyDir,$pbsDir,$mdlDir)) {
            if (Test-Path $d) {
              $it = Get-Item $d -ErrorAction SilentlyContinue
              if ($it -and -not $it.PSIsContainer) { Remove-Item $d -Force -ErrorAction SilentlyContinue }
            }
            New-Item -ItemType Directory -Path $d -Force | Out-Null
          }
          Set-Content -LiteralPath (Join-Path $pbsDir 'ok') -Value 'ok' -Encoding ascii -Force

      # ---------------- Build App (NSIS + Portable) ----------------
      - name: Build App (nsis + portable, no publish)
        if: ${{ hashFiles('package.json') != '' }}
        shell: pwsh
        run: |
          npx electron-builder --win nsis portable --x64 --publish never

      # ---------------- Compute tag ----------------
      - name: Compute tag
        id: tag
        shell: pwsh
        run: |
          $inputTag = '${{ inputs.tag }}'
          if ([string]::IsNullOrWhiteSpace($inputTag)) {
            $tag = 'v' + $env:GITHUB_RUN_NUMBER
          } else {
            $tag = $inputTag
          }
          "tag=$tag" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8

      # ---------------- Create/Update Release (App assets) ----------------
      - name: Create/Update Release (App)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: ${{ steps.tag.outputs.tag }}
          prerelease: ${{ inputs.prerelease }}
          # 這裡會抓 NSIS 安裝檔 + Portable exe + 其他壓縮檔（視你的 build 設定而定）
          files: |
            dist/*Setup*.exe
            dist/*-portable*.exe
            dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ---------------- Download model from HuggingFace ----------------
      - name: Install deps for model download
        shell: pwsh
        run: |
          python -m pip install -U pip
          python -m pip install "huggingface_hub>=0.22.0" hf_transfer

      - name: Download SDXL-Turbo model
        shell: pwsh
        env:
          HF_HUB_ENABLE_HF_TRANSFER: 1
        run: |
          $target = Join-Path (Get-Location).Path 'python\models\sd-turbo'
          $code = @'
          from huggingface_hub import snapshot_download
          import os
          tgt = os.environ["TARGET_DIR"]
          snapshot_download(
              repo_id="stabilityai/sdxl-turbo",
              local_dir=tgt,
              local_dir_use_symlinks=False
          )
          print("Model saved to:", tgt)
          '@
          Set-Content -Path download_model.py -Value $code -Encoding UTF8
          $env:TARGET_DIR = $target
          python download_model.py

      # ---------------- 7-Zip (900MB volumes) ----------------
      - name: Ensure 7-Zip
        shell: pwsh
        run: |
          $seven = "$env:ProgramFiles\7-Zip\7z.exe"
          if (-not (Test-Path $seven)) {
            choco install 7zip -y --no-progress
          }

      - name: Pack model into 7z (900MB parts)
        shell: pwsh
        run: |
          $seven = "$env:ProgramFiles\7-Zip\7z.exe"
          if (-not (Test-Path $seven)) { throw "7z.exe not found" }
          $src = Join-Path (Get-Location).Path 'python\models\sd-turbo\*'
          $dst = Join-Path (Get-Location).Path 'dist\model-pack.7z'
          # -mx=1 較快；若要更高壓縮可改 -mx=5~9，時間會變長
          & $seven a -t7z -m0=lzma2 -mx=1 -ms=off -v900m $dst $src
          if ($LASTEXITCODE -ne 0) { throw "7z create failed: $LASTEXITCODE" }

      # ---------------- Upload model parts to the same Release ----------------
      - name: Upload model pack parts to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          files: |
            dist/model-pack.7z.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ---------------- Optional: upload logs (best-effort) ----------------
      - name: Upload logs (best-effort)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: |
            logs/**/*.log
          if-no-files-found: ignore
