name: Release (Win + model, GitHub Releases)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g. v1.2.3; 留空則自動產生)"
        required: false
        default: ""

permissions:
  contents: write

jobs:
  release-windows:
    runs-on: windows-latest
    timeout-minutes: 120
    env:
      APP_DIR: ${{ github.workspace }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node deps
        shell: pwsh
        run: |
          if (Test-Path 'package-lock.json') { npm ci } else { npm i }

      - name: Ensure pbs marker exists
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path "python\models\sd-turbo" | Out-Null
          Set-Content -Path "python/pbs" -Value "ok" -Encoding ascii

      - name: Download SDXL-Turbo model
        shell: pwsh
        run: |
          python -m pip install -U pip huggingface_hub hf_transfer
          python - << 'PY'
          import os
          from huggingface_hub import snapshot_download
          os.environ['HF_HUB_ENABLE_HF_TRANSFER'] = '1'
          target = os.path.join('python','models','sd-turbo')
          os.makedirs(target, exist_ok=True)
          snapshot_download(repo_id='stabilityai/sdxl-turbo', local_dir=target, local_dir_use_symlinks=False)
          print('Model saved to', target)
          PY

      - name: Build installer
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          npx electron-builder --win --x64 --publish=never *>&1 | Tee-Object -FilePath "$env:GITHUB_WORKSPACE\eb.log"

      - name: Create tag (optional)
        if: ${{ inputs.tag != '' }}
        shell: pwsh
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "${{ inputs.tag }}"
          git push origin "${{ inputs.tag }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag != '' && inputs.tag || github.ref_name != 'refs/heads/main' && github.ref_name || format('v{0}', github.run_number) }}
          make_latest: true
          files: |
            dist/*.exe
            dist/*.zip
            eb.log
