name: Release (Win + model, GitHub Releases)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  smoke:
    runs-on: windows-latest
    steps:
      - name: Say hi
        run: echo "release workflow ok"
